// src/components/svelte/Navbar.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  let scrolled = $state(false);
  let menuOpen = $state(false);
  let activeSection = $state('hero');

  const navItems = [
    { id: 'hero', label: 'Inicio' },
    { id: 'about', label: 'Nosotros' },
    { id: 'car', label: 'El Coche' },
    { id: 'team', label: 'Equipo' },
    { id: 'gallery', label: 'Galería' },
    { id: 'sponsors', label: 'Patrocinio' },
    { id: 'contact', label: 'Contacto' },
  ];

  function scrollTo(id: string) {
    const el = document.getElementById(id);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth' });
      menuOpen = false;
    }
  }

  onMount(() => {
    const handleScroll = () => {
      scrolled = window.scrollY > 50;

      const sections = navItems.map(item => ({
        id: item.id,
        el: document.getElementById(item.id)
      })).filter(s => s.el);

      for (let i = sections.length - 1; i >= 0; i--) {
        const rect = sections[i].el!.getBoundingClientRect();
        if (rect.top <= 150) {
          activeSection = sections[i].id;
          break;
        }
      }
    };

    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  });
</script>

<nav
  class="fixed top-0 left-0 right-0 z-50 transition-all duration-500 {scrolled ? 'bg-[#0a0a0a]/90 backdrop-blur-md shadow-lg shadow-[#28629B]/10' : ''}"
>
  <div class="mx-auto max-w-7xl px-6 py-4 flex items-center justify-between">
    <!-- Logo -->
    <button onclick={() => scrollTo('hero')} class="relative z-50 group" data-hover>
      <span class="font-heading text-2xl tracking-widest text-boam-white group-hover:text-boam-blue transition-colors duration-300">
        BOAM
      </span>
      <span class="font-heading text-2xl tracking-widest text-boam-blue group-hover:text-boam-white transition-colors duration-300">
        RACING
      </span>
    </button>

    <!-- Desktop Nav -->
    <div class="hidden lg:flex items-center gap-1">
      {#each navItems as item}
        <button
          onclick={() => scrollTo(item.id)}
          class="relative px-4 py-2 text-sm font-medium tracking-wide uppercase transition-colors duration-300 {activeSection === item.id ? 'text-boam-blue' : 'text-boam-gray-light hover:text-boam-white'}"
          data-hover
        >
          {item.label}
          {#if activeSection === item.id}
            <span class="absolute bottom-0 left-1/2 -translate-x-1/2 w-4 h-0.5 bg-boam-blue rounded-full"></span>
          {/if}
        </button>
      {/each}
    </div>

    <!-- Mobile Menu Toggle -->
    <button
      onclick={() => menuOpen = !menuOpen}
      class="relative z-50 lg:hidden w-10 h-10 flex flex-col items-center justify-center gap-1.5"
      data-hover
      aria-label="Menu"
    >
      <span
        class="block w-6 h-0.5 bg-boam-white transition-all duration-300 origin-center {menuOpen ? 'rotate-45 translate-y-2' : ''}"
      ></span>
      <span
        class="block w-6 h-0.5 bg-boam-white transition-all duration-300 {menuOpen ? 'opacity-0' : ''}"
      ></span>
      <span
        class="block w-6 h-0.5 bg-boam-white transition-all duration-300 origin-center {menuOpen ? '-rotate-45 -translate-y-2' : ''}"
      ></span>
    </button>
  </div>

  <!-- Mobile Menu -->
  {#if menuOpen}
    <div
      class="fixed inset-0 bg-[#0a0a0a]/98 backdrop-blur-xl z-40 flex items-center justify-center lg:hidden"
    >
      <div class="flex flex-col items-center gap-6">
        {#each navItems as item, i}
          <button
            onclick={() => scrollTo(item.id)}
            class="font-heading text-4xl tracking-widest uppercase text-boam-gray-light hover:text-boam-blue transition-colors duration-300"
            style="animation: fade-up 0.5s {0.1 + i * 0.08}s var(--ease-out-expo) both"
            data-hover
          >
            {item.label}
          </button>
        {/each}
      </div>
    </div>
  {/if}
</nav>

// src/components/Navbar.tsx
"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import TopoButton from "@/components/ui/TopoButton";

export default function Navbar() {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const navLinks = [
    { name: "Home", href: "/" },
    { name: "El Equipo", href: "/equipo" },
    { name: "Patrocinio", href: "/patrocinio" },
    { name: "Media", href: "/media" },
  ];

  return (
    <nav
      className={`fixed top-0 left-0 w-full z-50 transition-all duration-300 ease-in-out ${
        isScrolled
          ? "bg-[var(--color-bg-sand)]/95 backdrop-blur-md shadow-sm py-4"
          : "bg-[var(--color-bg-dark)]/55 backdrop-blur-sm py-6"
      }`}
    >
      <div className="max-w-7xl mx-auto px-6 md:px-16 flex items-center justify-between">
        {/* Logo */}
        <Link href="/" className="group relative z-50">
          <span className="font-heading text-xl tracking-[4px] text-[var(--color-text-light)]"
            style={{ transition: "color 0.3s" }}
          >
            <span className={isScrolled ? "text-[var(--color-text-primary)]" : "text-[var(--color-text-light)]"}>UNIRAID TEAM</span>
          </span>
        </Link>

        {/* Desktop Navigation */}
        <div className="hidden md:flex items-center gap-8">
          <ul className="flex gap-8">
            {navLinks.map((link) => (
              <li key={link.name}>
                <Link
                  href={link.href}
                  className={`font-body text-sm uppercase tracking-[3px] transition-colors relative group ${
                    isScrolled
                      ? "text-[var(--color-text-primary)]/70 hover:text-[var(--color-text-primary)]"
                      : "text-[var(--color-text-light)]/70 hover:text-[var(--color-text-light)]"
                  }`}
                >
                  {link.name}
                  <span className="absolute -bottom-1 right-0 w-0 h-px bg-[var(--color-rust)] transition-all duration-300 group-hover:w-full group-hover:left-0"></span>
                </Link>
              </li>
            ))}
          </ul>

          <TopoButton>
            <Link
              href="/patrocinio"
              className="block px-8 py-3 bg-[var(--color-rust)] text-[var(--color-text-light)] font-body text-xs uppercase tracking-[3px] font-semibold transition-colors hover:bg-[var(--color-bg-dark)]"
            >
              Patrocinar
            </Link>
          </TopoButton>
        </div>

        {/* Mobile Menu Button */}
        <button
          className="md:hidden relative z-50"
          onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
          aria-label="Toggle Menu"
        >
          <div className="w-8 h-6 flex flex-col justify-between items-end">
            <span className={`h-0.5 transition-all duration-300 ${isMobileMenuOpen ? "w-8 rotate-45 translate-y-2.5 bg-[var(--color-text-light)]" : `w-8 ${isScrolled ? "bg-[var(--color-text-primary)]" : "bg-[var(--color-text-light)]"}`}`}></span>
            <span className={`h-0.5 transition-all duration-300 ${isMobileMenuOpen ? "opacity-0" : `w-6 ${isScrolled ? "bg-[var(--color-text-primary)]" : "bg-[var(--color-text-light)]"}`}`}></span>
            <span className={`h-0.5 transition-all duration-300 ${isMobileMenuOpen ? "w-8 -rotate-45 -translate-y-2.5 bg-[var(--color-text-light)]" : `w-4 ${isScrolled ? "bg-[var(--color-text-primary)]" : "bg-[var(--color-text-light)]"}`}`}></span>
          </div>
        </button>
      </div>

      {/* Mobile Menu Overlay */}
      <div
        className={`fixed inset-0 bg-[var(--color-bg-dark)] z-40 flex flex-col items-center justify-center transition-all duration-500 ease-in-out md:hidden ${
          isMobileMenuOpen ? "opacity-100 visible" : "opacity-0 invisible pointer-events-none"
        }`}
      >
        <div className="absolute inset-0 topo-bg opacity-5 pointer-events-none"></div>
        <ul className="flex flex-col items-center justify-center space-y-8 z-10 w-full px-6">
          {navLinks.map((link) => (
            <li key={link.name} className="w-full text-center">
              <Link
                href={link.href}
                className="font-heading text-4xl text-[var(--color-text-light)] hover:text-[var(--color-rust)] transition-colors block tracking-wider"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                {link.name}
              </Link>
            </li>
          ))}
          <li className="pt-8 w-full flex justify-center">
            <Link
              href="/patrocinio"
              className="inline-block px-12 py-4 bg-[var(--color-rust)] text-[var(--color-text-light)] font-body uppercase tracking-[3px] text-sm font-semibold"
              onClick={() => setIsMobileMenuOpen(false)}
            >
              Patrocinar
            </Link>
          </li>
        </ul>
      </div>
    </nav>
  );
}
